version: '3.1'

services:

  db:
    image: mysql:8.0.36-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: schoolsystem
    ports:
      - 3306:3306
