version: '3.1'

services:
  api:
    image: silviocavalcanti/schoolsystem:0.0.1-SNAPSHOT 
    container_name: api
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=schoolsystem
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    command: >
      bash -c "dockerize -wait tcp://db:3306 -timeout 240s"
    networks:
      - apinetwork
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0.36-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: schoolsystem
    networks:
      - apinetwork

networks:
  apinetwork:
    name: apinetwork